export const styles = {
  container: {
    flex: 1,
    backgroundColor: "#FCFCFD",
  },
  header: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 16,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold" as const,
    color: "#000",
    fontFamily: "Rubik-Bold",
  },
  filterButton: {
    padding: 8,
  },
  categorySelectorContainer: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  categorySelectorContent: {
    paddingRight: 20,
    gap: 8,
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    marginRight: 8,
  },
  categoryChipActive: {
    backgroundColor: "#0F766E",
    borderColor: "#0F766E",
  },
  categoryChipText: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: "#1F2937",
    fontFamily: "Rubik-SemiBold",
  },
  categoryChipTextActive: {
    color: "#FFFFFF",
  },
  postsContainer: {
    flex: 1,
    paddingHorizontal: 20,
  },
  postContainer: {
    backgroundColor: "white",
    marginBottom: 16,
    borderRadius: 12,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  userInfo: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginBottom: 12,
  },
  avatarContainer: {
    marginRight: 12,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E5E7EB",
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  avatarText: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: "#374151",
    fontFamily: "Rubik-Medium",
  },
  userDetails: {
    flex: 1,
  },
  userName: {
    fontSize: 16,
    fontWeight: "600" as const,
    color: "#111827",
    fontFamily: "Rubik-Medium",
  },
  forumBadge: {
    fontSize: 12,
    color: "#6B7280",
    fontFamily: "Rubik-Regular",
    marginTop: 2,
  },
  postActions: {
    flexDirection: "row" as const,
    gap: 8,
  },
  actionButton: {
    padding: 4,
  },
  postContent: {
    marginBottom: 12,
  },
  postText: {
    fontSize: 15,
    lineHeight: 22,
    color: "#374151",
    fontFamily: "Rubik-Regular",
  },
  timestamp: {
    fontSize: 12,
    color: "#6B7280",
    fontFamily: "Rubik-Regular",
    textAlign: "right" as const,
    marginTop: 8,
  },
  videoContainer: {
    marginTop: 12,
    borderRadius: 8,
    overflow: "hidden" as const,
  },
  videoThumbnail: {
    height: 120,
    backgroundColor: "#8B4513",
    justifyContent: "center" as const,
    alignItems: "center" as const,
    position: "relative" as const,
  },
  videoThumbnailText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold" as const,
    fontFamily: "Rubik-Bold",
  },
  playButton: {
    position: "absolute" as const,
    top: 200,
    left: 200,
    transform: [{ translateX: -12 }, { translateY: -12 }],
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  videoTitle: {
    fontSize: 14,
    fontWeight: "600" as const,
    color: "#111827",
    fontFamily: "Rubik-Medium",
    marginTop: 8,
    marginBottom: 4,
  },
  videoUrl: {
    fontSize: 12,
    color: "#3B82F6",
    fontFamily: "Rubik-Regular",
  },
  interactionBar: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  leftInteractions: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
  },
  interactionButton: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginRight: 20,
  },
  interactionText: {
    fontSize: 14,
    color: "#6B7280",
    fontFamily: "Rubik-Regular",
    marginLeft: 4,
  },
  greaterThanIcon: {
    fontSize: 18,
    color: "#666",
    fontFamily: "Rubik-Regular",
    fontWeight: "bold" as const,
  },
  startConversationContainer: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    backgroundColor: "white",
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  plusButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F3F4F6",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    marginRight: 12,
  },
  conversationInput: {
    flex: 1,
    fontSize: 15,
    color: "#374151",
    fontFamily: "Rubik-Regular",
    paddingVertical: 8,
  },
  micButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F3F4F6",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    marginLeft: 12,
  },
  bottomNavOverlay: {
    position: "absolute" as const,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    backgroundColor: "transparent",
  },
  avatarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  embeddedLinksContainer: {
    marginTop: 12,
  },
  videoDescription: {
    fontSize: 13,
    color: "#6B7280",
    fontFamily: "Rubik-Regular",
    marginTop: 4,
  },
  sendButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#E8F8F5",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    marginLeft: 12,
  },
  // Loading, Error, and Empty States
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#6B7280",
    fontFamily: "Rubik-Regular",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: "bold" as const,
    color: "#1F2937",
    marginTop: 16,
    fontFamily: "Rubik-Bold",
  },
  errorText: {
    fontSize: 14,
    color: "#6B7280",
    textAlign: "center" as const,
    marginTop: 8,
    fontFamily: "Rubik-Regular",
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyStateWithPostInput: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 40,
  },
  emptyStateMessage: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: "bold" as const,
    color: "#1F2937",
    marginTop: 24,
    fontFamily: "Rubik-Bold",
  },
  emptyText: {
    fontSize: 16,
    color: "#6B7280",
    textAlign: "center" as const,
    marginTop: 12,
    marginBottom: 32,
    lineHeight: 24,
    fontFamily: "Rubik-Regular",
  },
  createForumButtonInEmpty: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: "#256E63",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    gap: 8,
  },
  createForumButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600" as const,
    fontFamily: "Rubik-SemiBold",
  },
  footerLoader: {
    paddingVertical: 20,
    alignItems: "center" as const,
  },
  editModal: {
    position: "absolute" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center" as const,
    alignItems: "center" as const,
    zIndex: 1000,
  },
  editModalContent: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 20,
    width: "90%",
    maxHeight: "80%",
  },
  editModalHeader: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    marginBottom: 16,
  },
  editModalTitle: {
    fontSize: 20,
    fontWeight: "bold" as const,
    color: "#111827",
    fontFamily: "Rubik-Bold",
  },
  closeButton: {
    padding: 4,
  },
  editInput: {
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    padding: 12,
    fontSize: 15,
    color: "#374151",
    fontFamily: "Rubik-Regular",
    minHeight: 100,
    textAlignVertical: "top" as const,
    marginBottom: 16,
  },
  editModalActions: {
    flexDirection: "row" as const,
    justifyContent: "flex-end" as const,
    gap: 12,
  },
  editButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    minWidth: 80,
    alignItems: "center" as const,
  },
  cancelEditButton: {
    backgroundColor: "#F3F4F6",
  },
  cancelEditButtonText: {
    color: "#374151",
    fontWeight: "600" as const,
    fontSize: 14,
    fontFamily: "Rubik-SemiBold",
  },
  saveEditButton: {
    backgroundColor: "#256E63",
  },
  saveEditButtonText: {
    color: "#fff",
    fontWeight: "600" as const,
    fontSize: 14,
    fontFamily: "Rubik-SemiBold",
  },
  createForumModal: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end" as const,
  },
  createForumModalContent: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 40,
    maxHeight: "90%",
  },
  createForumModalHeader: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  createForumModalTitle: {
    fontSize: 22,
    fontWeight: "bold" as const,
    color: "#111827",
    fontFamily: "Rubik-Bold",
  },
  createForumForm: {
    paddingBottom: 16,
  },
  createForumLabel: {
    fontSize: 16,
    fontWeight: "600" as const,
    color: "#1F2937",
    fontFamily: "Rubik-SemiBold",
    marginBottom: 8,
    marginTop: 16,
  },
  createForumInput: {
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: "#111827",
    fontFamily: "Rubik-Regular",
    backgroundColor: "#F9FAFB",
  },
  createForumTextArea: {
    minHeight: 120,
    textAlignVertical: "top" as const,
  },
  createForumHelperText: {
    fontSize: 12,
    color: "#6B7280",
    fontFamily: "Rubik-Regular",
    marginTop: 4,
  },
  createForumScroll: {
    maxHeight: 360,
    marginBottom: 24,
  },
  createForumScrollContent: {
    paddingBottom: 16,
  },
  createForumCategoryLoading: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginTop: 8,
  },
  createForumCategoryLoadingText: {
    marginLeft: 8,
    fontSize: 14,
    color: "#4B5563",
    fontFamily: "Rubik-Regular",
  },
  createForumCategoryList: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    marginTop: 8,
  },
  createForumCategoryChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: "#F9FAFB",
    marginRight: 8,
    marginBottom: 8,
  },
  createForumCategoryChipActive: {
    borderColor: "#256E63",
    backgroundColor: "#E8F8F5",
  },
  createForumCategoryChipText: {
    fontSize: 14,
    color: "#374151",
    fontFamily: "Rubik-Regular",
  },
  createForumCategoryChipTextActive: {
    color: "#0F766E",
    fontFamily: "Rubik-SemiBold",
  },
  createForumModalActions: {
    flexDirection: "row" as const,
    gap: 12,
  },
  cancelForumButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: "#F3F4F6",
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  cancelForumButtonText: {
    color: "#374151",
    fontWeight: "600" as const,
    fontSize: 16,
    fontFamily: "Rubik-SemiBold",
  },
  submitForumButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: "#256E63",
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  submitForumButtonDisabled: {
    backgroundColor: "#9CA3AF",
    opacity: 0.6,
  },
  submitForumButtonText: {
    color: "#fff",
    fontWeight: "600" as const,
    fontSize: 16,
    fontFamily: "Rubik-SemiBold",
  },
};
